# Generated by Django 2.2.4 on 2021-03-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteDashApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='title',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='quotes',
            old_name='desc',
            new_name='quote',
        ),
    ]
